version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - GUNICORN_TIMEOUT=120
      - GUNICORN_WORKERS=1
    # Add memory limit
    deploy:
      resources:
        limits:
          memory: 512M